name: Node.js

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [14, 16, 20, latest]

    steps:
      - uses: actions/checkout@v4
        with: { submodules: true }
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - if: matrix.node-version == 14
        run: npm install --global npm@7
      - run: npm ci
      - if: matrix.node-version < 18
        run: npm install --no-save rollup@3
      - run: npm test
      - run: npm run test:dist

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - run: npm run lint
