name: TypeScript

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  typescript:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with: { node-version: 16.x }
      - run: npm ci
      - run: npm run build:node
      - run: npm run test:types
      - run: npm run test:dist:types

      - run: npm install --no-save typescript@4.2
      - run: for d in node_modules/@types/*; do [[ $d == *node ]] || rm -r $d; done
      - run: npm run test:dist:types

      - run: npm install --no-save typescript@4.0
      - run: for d in node_modules/@types/*; do [[ $d == *node ]] || rm -r $d; done
      - run: npm run test:dist:types

      - run: npm install --no-save typescript@3.9
      - run: for d in node_modules/@types/*; do [[ $d == *node ]] || rm -r $d; done
      - run: npm run test:dist:types
